AzuronetBees.Web/Models/Bee.cs
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AzuronetBees.Web.Models
{
    public class Bee
    {
        [Key]
        public int BeeId { get; set; }

        [Required(ErrorMessage = "Proszę wybrać rasę pszczoły")]
        [Display(Name = "Rasa pszczół:")]
        public BreedOfBees? BreedOfBees { get; set; }

        [Required(ErrorMessage = "Proszę wpisz opis rodziny")]
        [Display(Name = "Opis:")]
        public string Description { get; set; }

        [Display(Name = "Rojliwość:")]
        public bool SwarmingBees { get; set; }

        [Display(Name = "Aktualna:")]
        public bool Active { get; set; }

        [Range(1, 10)]
        [Required(ErrorMessage = "Proszę ocenić całokształt rodziny")]
        [Display(Name = "Ocena ogólna:")]
        public int? Overall { get; set; }

        [NotMapped]
        [Display(Name = "Zdjęcie pszczoły:")]
        public IFormFile PhotoAvatar { get; set; }

        public string ImageName { get; set; }

        public byte[] PhotoFile { get; set; }

        public string ImageMimeType { get; set; }

        [Display(Name = "Ul:")]
        public int? BeehiveId { get; set; }

        public virtual Beehive Beehive { get; set; }
    }
}

AzuronetBees.Web/Models/Beehive.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AzuronetBees.Web.Models
{
    public class Beehive
    {
        [Key]
        public int BeehiveId { get; set; }

        [Required(ErrorMessage = "Proszę podać nazwę ula")]
        [StringLength(50, MinimumLength = 1)]
        [Display(Name = "Nazwa ula:")]
        public string BeehiveName { get; set; }

        [Required(ErrorMessage = "Proszę dodać opis ula")]
        [StringLength(200, MinimumLength = 1)]
        [Display(Name = "Opis:")]
        public string Description { get; set; }

        [StringLength(50, MinimumLength = 4)]
        [Display(Name = "Lokalizacja:")]
        public string Location { get; set; }

        public virtual ICollection<Bee> Bees { get; set; }
    }
}

AzuronetBees.Web/Models/BreedOfBees.cs
namespace AzuronetBees.Web.Models
{
    public enum BreedOfBees
    {
        Hinderhofer,
        Alpejka,
        Troiseck,
        Karpatka,
        Prima,
        Gema,
        Primorska,
        Sklenar,
        Celle
    }
}

AzuronetBees.Web/Models/ErrorViewModel.cs
using System;

namespace AzuronetBees.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AzuronetBees.Web/Controllers/BeeController.cs
using AzuronetBees.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using AzuronetBees.Web.Repositories;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AzuronetBees.Web.Controllers
{
    public class BeeController : Controller
    {
        private readonly ILogger<BeeController> _logger;
        private IBeeRepository _repository;
        private IWebHostEnvironment _environment;

        public BeeController (IBeeRepository repository)
        {
            _repository = repository;
        }

        public BeeController(ILogger<BeeController> logger, IBeeRepository repository, IWebHostEnvironment environment)
        {
            _logger = logger;
            _repository = repository;
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View(_repository.GetBees());
        }

        public IActionResult Details(int id)
        {
            var bee = _repository.GetBeeById(id);
            if (bee == null)
            {
                return NotFound();
            }
            return View(bee);
        }

       private void PopulateBeehivesDropDownList(int? selectedBeehive = null)
        {
            var beehives = _repository.PopulateBeehivesDropDownList();
            ViewBag.BeehiveID = new SelectList(beehives.AsNoTracking(), "BeehiveId", "BeehiveName", selectedBeehive);
        }

        [HttpGet]
        public IActionResult Create()
        {
            PopulateBeehivesDropDownList();
            return View();
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost(Bee bee)
        {
            if (ModelState.IsValid)
            {
                _repository.CreateBee(bee);
                return RedirectToAction(nameof(Index));
            }
            PopulateBeehivesDropDownList(bee.BeehiveId);
            return View(bee);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Bee bee = _repository.GetBeeById(id);
            if (bee == null)
            {
                return NotFound();
            }
            PopulateBeehivesDropDownList(bee.BeehiveId);
            return View(bee);
        }

        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(int id)
        {
            var beeToUpdate = _repository.GetBeeById(id);
            bool isUpdated = await TryUpdateModelAsync<Bee>(
                                     beeToUpdate,
                                     "",
                                     b => b.BeehiveId,
                                     b => b.BreedOfBees,
                                     b => b.Description,
                                     b => b.SwarmingBees,
                                     b => b.Active,
                                     b => b.Overall);
            if (isUpdated == true)
            {
                _repository.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            PopulateBeehivesDropDownList(beeToUpdate.BeehiveId);
            return View(beeToUpdate);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var bee = _repository.GetBeeById(id);
            if (bee == null)
            {
                return NotFound();
            }
            return View(bee);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _repository.DeleteBee(id);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult GetImage(int id)
        {
            Bee requestedBee = _repository.GetBeeById(id);
            if (requestedBee != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedBee.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedBee.ImageMimeType);
                }
                else
                {
                    if (requestedBee.PhotoFile.Length > 0)
                    {
                        return File(requestedBee.PhotoFile, requestedBee.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AzuronetBees.Web/Views/Bee/Create.cshtml
@using AzuronetBees.Web.Models
@model AzuronetBees.Web.Models.Bee

@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Dodanie nowej rodziny</title>
    <link type="text/css" rel="stylesheet" href="~/css/bee-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class="main-titel">Dodaj rodzinę pszczelą do pasieki</h1>
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="All"></div>
            <div class="form-field">
                <label asp-for="BeehiveId"></label>
                <select asp-for="BeehiveId" asp-items="ViewBag.BeehiveID">
                    <option selected="selected" value="">Wybierz</option>
                </select>
                <span asp-validation-for="BeehiveId"></span>
            </div>
            <div class="form-field">
                <label asp-for="BreedOfBees"></label>
                <select asp-for="BreedOfBees" asp-items="Html.GetEnumSelectList<BreedOfBees>()">
                    <option selected="selected" value="">Wybierz</option>
                </select>
                <span asp-validation-for="BreedOfBees"></span>
            </div>
            <div class="form-field">
                <label asp-for="Description"></label>
                <textarea asp-for="Description"></textarea>
                <span asp-validation-for="Description"></span>
            </div>
            <div class="form-field">
                <label asp-for="SwarmingBees"></label>
                <input asp-for="SwarmingBees" />
                <span asp-validation-for="SwarmingBees"></span>
            </div>
            <div class="form-field">
                <label asp-for="Active"></label>
                <input asp-for="Active" />
                <span asp-validation-for="Active"></span>
            </div>
            <div class="form-field">
                <label asp-for="Overall"></label>
                <input asp-for="Overall" />
                <span asp-validation-for="Overall"></span>
            </div>
            <div class="form-field">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" type="file" />
                <span asp-validation-for="PhotoAvatar"></span>
            </div>
            <div class="form-field">
                <input type="submit" value="Zapisz zmiany" />
            </div>
        </form>
    </div>
</body>
</html>

AzuronetBees.Web/Views/Bee/Delete.cshtml
@model AzuronetBees.Web.Models.Bee

@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Usuwanie rodziny pszczelej</title>
    <link type="text/css" rel="stylesheet" href="~/css/bee-styles.css" />
</head>
<body>
    <div class="container">
        <h3 class="into">Czy na pewno chcesz usunąć tą rodzinę pszczelą?</h3>
        <div class="photo-index-card-details">
            <h3 class="display-picture-title">
                "@Html.DisplayFor(modelItem => modelItem.BreedOfBees)"
            </h3>
            @if (Model.ImageName != null)
            {
                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Bee", new { Id = Model.BeeId })" />
                </div>}
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </p>
                <br />
                <p class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.SwarmingBees)
                </p>
                <br />
                <p class="display-field">
                    @Html.DisplayFor(model => model.SwarmingBees)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Active)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.Active)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Overall)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.Overall)
                </p>
            </div>
        </div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="BeeId" />
            <input type="submit" value="Usuń" /> |
            <a asp-action="Index">Powrót do strony głównej</a>
        </form>
    </div>
</body>
</html>

AzuronetBees.Web/Views/Bee/Details.cshtml
@model AzuronetBees.Web.Models.Bee

@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Szczegóły rodziny pszczelej</title>
    <link type="text/css" rel="stylesheet" href="~/css/bee-styles.css" />
</head>
<body>
    <div class="container">
        <div class="photo-index-card-details">
            <h3 class="display-picture-title">
                "@Html.DisplayFor(modelItem => modelItem.BreedOfBees)"
            </h3>
            @if (Model.ImageName != null)
            {
                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Bee", new { Id = Model.BeeId })" />
                </div>}
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Description)
                </p>
                <br />
                <p class="display-field">
                    @Html.DisplayFor(model => model.Description)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.SwarmingBees)
                </p>
                <br />
                <p class="display-field">
                    @Html.DisplayFor(model => model.SwarmingBees)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Active)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.Active)
                </p>
            </div>
            <div>
                <p class="display-label">
                    @Html.DisplayNameFor(model => model.Overall)
                </p>
                <p class="display-field">
                    @Html.DisplayFor(model => model.Overall)
                </p>
            </div>
            <div>
                <a asp-action="Index">Powrót do strony głównej</a>
            </div>
        </div>
    </div>
</body>
</html>

AzuronetBees.Web/Views/Bee/Edit.cshtml
@using AzuronetBees.Web.Models
@model AzuronetBees.Web.Models.Bee

@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edycja</title>
    <link type="text/css" rel="stylesheet" href="~/css/bee-styles.css" />
</head>
<body>
    <div class="container">
        <h1 class="title">Edycja rodziny pszczelej</h1>
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly"></div>
            <input type="hidden" asp-for="BeeId" />
            <div class="form-field">
                <label asp-for="Beehive"></label>
                <select asp-for="BeehiveId" asp-items="ViewBag.BeehiveID">
                    <option selected="selected" value="">Select</option>
                </select>
                <span asp-validation-for="BeehiveId"></span>
            </div>
            <div class="form-field">
                <label asp-for="BreedOfBees"></label>
                <select asp-for="BreedOfBees" asp-items="Html.GetEnumSelectList<BreedOfBees>()">
                    <option selected="selected" value="">Select</option>
                </select>
                <span asp-validation-for="BreedOfBees"></span>
            </div>
            <div class="form-field">
                <label asp-for="Description"></label>
                <textarea asp-for="Description"></textarea>
                <span asp-validation-for="Description"></span>
            </div>
            <div class="form-field">
                <label asp-for="SwarmingBees"></label>
                <input asp-for="SwarmingBees" />
                <span asp-validation-for="SwarmingBees"></span>
            </div>
            <div class="form-field">
                <label asp-for="Active"></label>
                <input asp-for="Active" />
                <span asp-validation-for="Active"></span>
            </div>
            <div class="form-field">
                <label asp-for="Overall"></label>
                <input asp-for="Overall" />
                <span asp-validation-for="Overall"></span>
            </div>
            <div>
                <input type="hidden" asp-for="ImageMimeType" />
                <input type="hidden" asp-for="ImageName" />
                @Html.HiddenFor(b => b.PhotoAvatar)
                @Html.HiddenFor(b => b.PhotoFile)
            </div>
            <div class="form-field">
                <input type="submit" value="Zapisz zmiany" />
            </div>
        </form>
    </div>
</body>
</html>

AzuronetBees.Web/Views/Bee/Index.cshtml
@model IEnumerable<AzuronetBees.Web.Models.Bee>

@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Strona główna aplikacji do zarządzania pasieką</title>
    <link type="text/css" rel="stylesheet" href="~/css/bee-styles.css" />
</head>
<body>
    <div class="container">
        <div class="main-title">
            <p class="into">Witamy w Pasiece na Roztoczu</p>
            <button type="button" onclick="location.href='@Url.Action("Create", "Bee")'">Dodaj rodzinę</button>
        </div>
        <div class="img-container">
            @foreach (var item in Model)
            {
                <div class="photo-index-card">
                <h3 class="display-picture-title">
                "@Html.DisplayFor(modelItem => item.BreedOfBees)"
                </h3>
            @if (item.ImageName != null)
             {
<div class="photo-display">
    <img class="photo-display-img" src="@Url.Action("GetImage", "Bee", new { Id = item.BeehiveId })" />
</div>}
    <div>
        <p class="display-label">
            @Html.DisplayNameFor(model => item.Description)
        </p>
        <br />
        <p class="display-field">
            @Html.DisplayFor(model => item.Description)
        </p>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@item.BeeId">Edycja</a> |
        <a asp-action="Details" asp-route-id="@item.BeeId">Szczegóły</a> |
        <a asp-action="Delete" asp-route-id="@item.BeeId">Usuwanie</a>
    </div>
</div>      }
        </div>
    </div>
</body>
</html>

AzuronetBees.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AzuronetBees.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AzuronetBees.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AzuronetBees.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>